import { createSlice, current } from "@reduxjs/toolkit";


const productDataSlice = createSlice({
    name: "productData",
    initialState: {
        productsData: [
            {
                id: 1,
                deals: true,
                image: '/images/deals_img1.jpg',
                name: 'Smart Speaker with Alexa Voice Control Built-in',
                oldPrice: 7999, // Old price in INR
                currentPrice: 6999, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 6999,
                quantityCounter: 1,
                description: 'Enjoy immersive audio and control your smart home with this smart speaker featuring built-in Alexa voice control.',
                rating: 4.5,
            },
            {
                id: 2,
                company: 'boat',
                deals: true,
                image: '/images/deals_img2.jpeg',
                name: 'Compact Size Wireless Earbuds with Noise Cancelling',
                oldPrice: 6499, // Old price in INR
                currentPrice: 5499, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 5499,
                quantityCounter: 1,
                description: 'Experience superior sound quality and noise cancellation with these compact wireless earbuds.',
                rating: 4,
            },
            {
                id: 3,
                company: 'sony',
                deals: true,
                tv: 'true',
                image: '/images/deals_img3.avif',
                name: 'Ultra HD Smart TV with HDR and Dolby Vision',
                oldPrice: 61990, // Old price in INR
                currentPrice: 56990, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 56990,
                quantityCounter: 1,
                description: 'Immerse yourself in stunning visuals with this Ultra HD Smart TV featuring HDR and Dolby Vision technology.',
                rating: 3,
            },
            {
                id: 4,
                deals: true,
                image: '/images/deals_img4.jpg',
                name: 'Wireless Charging Pad for Qi-Enabled Devices',
                oldPrice: 1499, // Old price in INR
                currentPrice: 1299, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 1299,
                quantityCounter: 1,
                description: 'Charge your Qi-enabled devices wirelessly with this convenient and stylish wireless charging pad.',
                rating: 5,
            },
            {
                id: 5,
                deals: true,
                image: '/images/deals_img5.avif',
                name: 'Smartphone with Dual Camera and Face Recognition',
                oldPrice: 27999, // Old price in INR
                currentPrice: 24999, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 24999,
                quantityCounter: 1,
                description: 'Capture stunning photos with the dual camera setup and unlock your phone securely using face recognition on this smartphone.',
                rating: 2.5,
            },
            {
                id: 6,
                company: 'boat',
                deals: true,
                image: '/images/deals_img6.jpg',
                name: 'Bluetooth Noise Cancelling Headphones',
                oldPrice: 4499, // Old price in INR
                currentPrice: 3999, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 3999,
                quantityCounter: 1,
                description: 'Immerse yourself in your favorite music without distractions with these Bluetooth noise-canceling headphones.',
                rating: 3,
            },
            {
                id: 7,
                company: 'asus',
                deals: true,
                image: '/images/deals_img7.jpg',
                name: 'Gaming Laptop with High-Performance Graphics',
                oldPrice: 89999, // Old price in INR
                currentPrice: 79999, // Current price in INR
                estimatedTime: "9 june 2050",
                isFavorite: false,
                cartTotal: 79999,
                quantityCounter: 1,
                description: 'Experience smooth gaming and graphics-intensive tasks with this high-performance gaming laptop.',
                rating: 3.5,
            },
            {
                "id": 8,
                "company": "panasonic",
                "deals": true,
                "image": "/images/deals_img8.jpg",
                "name": "Smart Home Security Camera System",
                "oldPrice": 6499,
                "currentPrice": 5999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 5999,
                "quantityCounter": 1,
                "description": "Keep your home secure with this smart home security camera system featuring advanced surveillance features.",
                "rating": 4
            },
            {
                "id": 11,
                "company": "samsung",
                "av": true,
                "image": "/images/av_img1.webp",
                "name": "Home Theater Soundbar with Subwoofer",
                "oldPrice": 7999,
                "currentPrice": 6999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 6999,
                "quantityCounter": 1,
                "description": "Enhance your home entertainment experience with this powerful home theater soundbar featuring a built-in subwoofer. Immerse yourself in rich, high-quality audio as you watch movies, listen to music, or play games.",
                "rating": 5
            },
            {
                "id": 12,
                "av": true,
                "company": "sony",
                "image": "/images/av_img2.webp",
                "name": "Wireless Surround Soundbar System",
                "oldPrice": 6499,
                "currentPrice": 5499,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 5499,
                "quantityCounter": 1,
                "description": "Immerse yourself in cinematic sound with this wireless surround soundbar system for an immersive audio experience. This soundbar system features multiple speakers and wireless connectivity, allowing you to place the speakers around your room for a true surround sound effect. With advanced audio technologies, including Dolby Atmos and DTS:X, you'll feel like you're in the middle of the action. The wireless subwoofer adds deep, powerful bass to enhance your movie nights and gaming sessions.",
                "rating": 3
            },
            {
                "id": 13,
                "company": "sony",
                "av": true,
                "image": "/images/av_img3.jpg",
                "name": "55-Inch Smart LED TV with HDR",
                "oldPrice": 61990,
                "currentPrice": 56990,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 56990,
                "quantityCounter": 1,
                "description": "Enjoy stunning visuals and smart features with this 55-inch Smart LED TV featuring HDR technology. The high-resolution display brings your favorite movies and shows to life with vibrant colors and sharp details. With HDR support, you'll experience enhanced contrast and a wider range of colors for a more immersive viewing experience. The smart features allow you to stream your favorite content from popular apps and services. Connect external devices easily with multiple HDMI and USB ports.",
                "rating": 4
            },
            {
                "id": 14,
                "company": "samsung",
                "av": true,
                "image": "/images/av_img4.webp",
                "name": "65-Inch 4K Ultra HD Smart LED TV",
                "oldPrice": 89999,
                "currentPrice": 79999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 79999,
                "quantityCounter": 1,
                "description": "Immerse yourself in the world of entertainment with this 65-inch 4K Ultra HD Smart LED TV. The large display delivers stunning visuals with four times the resolution of Full HD, bringing every detail to life. HDR technology enhances contrast and color accuracy, making the images more vibrant and realistic. With built-in smart features, you can access a wide range of streaming services and enjoy your favorite content with ease. The TV is equipped with multiple HDMI and USB ports for seamless connectivity to gaming consoles, soundbars, and other devices.",
                "rating": 5
            },
            {
                "id": 15,
                "company": "samsung",
                "ha": true,
                "image": "/images/ha_img1.jpeg",
                "name": "Robot Vacuum Cleaner",
                "oldPrice": 4999,
                "currentPrice": 3999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 3999,
                "quantityCounter": 1,
                "description": "Make your cleaning routine effortless with this advanced robot vacuum cleaner. It intelligently navigates your home, reaching every corner and effectively picking up dirt, dust, and pet hair. With its powerful suction and multiple cleaning modes, it ensures thorough cleaning on various surfaces. The smart features allow you to schedule cleaning sessions and control the robot remotely through a mobile app. Sit back, relax, and let this robot vacuum cleaner take care of your cleaning needs.",
                "rating": 2
            },
            {
                "id": 16,
                "company": "panasonic",
                "ha": true,
                "image": "/images/ha_img2.jpg",
                "name": "Automatic Rice Cooker",
                "oldPrice": 2499,
                "currentPrice": 1999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 1999,
                "quantityCounter": 1,
                "description": "Simplify your cooking process with this automatic rice cooker. It features advanced technology that ensures perfectly cooked rice every time. With a large capacity, it can cook rice for the whole family. The cooker offers multiple cooking options, including different rice varieties and steaming functions. Its user-friendly interface and programmable timer make it convenient to use. Say goodbye to overcooked or undercooked rice and enjoy delicious, fluffy rice effortlessly.",
                "rating": 4.2
            },
            {
                "id": 17,
                "company": "samsung",
                "ha": true,
                "image": "/images/ha_img3.webp",
                "name": "Air Purifier with HEPA Filter",
                "oldPrice": 6999,
                "currentPrice": 5999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 5999,
                "quantityCounter": 1,
                "description": "Breathe cleaner air with this high-performance air purifier featuring a HEPA filter. It effectively captures allergens, dust, pet dander, and other pollutants, providing you with a healthier indoor environment. The purifier offers multiple fan speed settings and a timer for customized operation. With its compact design, it fits well in any room. Improve the air quality in your home and enjoy fresher, purer air with this reliable air purifier.",
                "rating": 4.7
            },
            {
                "id": 18,
                "company": "panasonic",
                "ha": true,
                "image": "/images/ha_img4.jpg",
                "name": "Smart Wi-Fi Enabled Thermostat",
                "oldPrice": 3499,
                "currentPrice": 2999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 2999,
                "quantityCounter": 1,
                "description": "Take control of your home's temperature with this smart Wi-Fi enabled thermostat. It allows you to easily program and adjust the temperature from anywhere using your smartphone or voice commands. With its intuitive interface and energy-saving features, you can optimize your home's comfort while reducing energy consumption. The thermostat also provides valuable insights and usage reports to help you make informed decisions. Make your home smarter and more energy-efficient with this innovative Wi-Fi enabled thermostat.",
                "rating": 4.5
            },
            {
                "id": 19,
                "company": "samsung",
                "ac": true,
                "image": "/images/ac_img1.jpg",
                "name": "Split Inverter Air Conditioner (1.5 Ton)",
                "oldPrice": 39999,
                "currentPrice": 34999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 34999,
                "quantityCounter": 1,
                "description": "Experience efficient cooling with this Split Inverter Air Conditioner. With a capacity of 1.5 Ton, it provides powerful cooling for your space. The inverter technology ensures energy efficiency and precise temperature control. Enjoy a comfortable indoor environment while saving on energy bills. This air conditioner features multiple modes and a user-friendly interface for convenient operation. Beat the heat with this reliable and high-performance air conditioner.",
                "rating": 4.8
            },
            {
                "id": 20,
                "company": "panasonic",
                "ac": true,
                "image": "/images/ac_img2.webp",
                "name": "Window Air Conditioner (1 Ton)",
                "oldPrice": 25999,
                "currentPrice": 22999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 22999,
                "quantityCounter": 1,
                "description": "Cool your room effectively with this Window Air Conditioner. It has a capacity of 1 Ton, making it suitable for small to medium-sized spaces. The compact design fits well in most windows, providing efficient cooling without occupying much space. This air conditioner offers multiple cooling modes and adjustable temperature settings for personalized comfort. Stay cool during the hot summer months with this convenient and affordable window air conditioner.",
                "rating": 4.3
            },
            {
                "id": 21,
                "company": "samsung",
                "ac": true,
                "image": "/images/ac_img3.jpg",
                "name": "Portable Air Conditioner (10,000 BTU)",
                "oldPrice": 19999,
                "currentPrice": 17999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 17999,
                "quantityCounter": 1,
                "description": "Stay cool and comfortable anywhere with this Portable Air Conditioner. With a cooling capacity of 10,000 BTU, it provides efficient cooling for small to medium-sized rooms. The portable design allows you to move it easily between rooms or spaces. This air conditioner features adjustable temperature settings, fan speeds, and a built-in dehumidifier for personalized comfort. Beat the summer heat and enjoy a pleasant indoor environment with this versatile portable air conditioner.",
                "rating": 4.6
            },
            {
                "id": 22,
                "company": "samsung",
                "ac": true,
                "image": "/images/ac_img4.jpg",
                "name": "Ductless Mini Split Air Conditioner (2 Ton)",
                "oldPrice": 56999,
                "currentPrice": 51999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 51999,
                "quantityCounter": 1,
                "description": "Experience efficient cooling with this Ductless Mini Split Air Conditioner. With a capacity of 2 Ton, it provides powerful and consistent cooling for your space. The ductless design offers flexibility in installation and ensures quiet operation. This air conditioner features advanced cooling technologies and smart controls for energy efficiency and convenience. Create a comfortable indoor environment while saving on energy costs with this high-performance ductless mini-split air conditioner.",
                "rating": 4.9
            },
            {
                "id": 23,
                "company": "panasonic",
                "ka": true,
                "image": "/images/ka1.jpg",
                "name": "Blender with Multiple Speeds",
                "oldPrice": 1999,
                "currentPrice": 1499,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 1499,
                "quantityCounter": 1,
                "description": "Create delicious and healthy smoothies, shakes, and more with this Blender. It features multiple speeds for precise blending control. The powerful motor ensures smooth and consistent blending results. The compact and stylish design makes it a great addition to any kitchen countertop. Simplify your blending tasks with this versatile blender.",
                "rating": 4.5
            },
            {
                "id": 24,
                "ka": true,
                "image": "/images/ka2.jpg",
                "name": "Electric Kettle with Temperature Control",
                "oldPrice": 1499,
                "currentPrice": 999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 999,
                "quantityCounter": 1,
                "description": "Boil water quickly and efficiently with this Electric Kettle. It comes with temperature control options, allowing you to heat water to your desired temperature for various beverages. The compact and sleek design makes it easy to use and store. Enjoy your favorite hot beverages with ease using this convenient electric kettle.",
                "rating": 4.2
            },
            {
                "id": 25,
                "company": "samsung",
                "ka": true,
                "image": "/images/ka3.jpg",
                "name": "Toaster Oven with Convection",
                "oldPrice": 3999,
                "currentPrice": 2999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 2999,
                "quantityCounter": 1,
                "description": "Prepare a variety of delicious meals with this Toaster Oven. It features convection technology for even and efficient cooking. The versatile oven allows you to bake, toast, and broil with ease. The compact design saves space on your kitchen countertop. Upgrade your cooking capabilities with this convenient toaster oven.",
                "rating": 4.7
            },
            {
                "id": 26,
                "company": "samsung",
                "ka": true,
                "image": "/images/ka4.avif",
                "name": "Refrigerator",
                "oldPrice": 53099,
                "currentPrice": 44099,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 44099,
                "quantityCounter": 1,
                "description": "Keep your food fresh and organized with this Refrigerator. It offers ample storage space and adjustable shelves to accommodate your groceries. The energy-efficient design helps reduce electricity costs. The sleek and modern appearance adds style to your kitchen. Upgrade your kitchen with this reliable and spacious refrigerator.",
                "rating": 4.4
            },
            {
                "id": 27,
                "company": "asus",
                "computer": true,
                "image": "/images/pl1.jpg",
                "name": "Gaming Laptop with High-Performance Graphics",
                "oldPrice": 89999,
                "currentPrice": 79999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 79999,
                "quantityCounter": 1,
                "description": "Experience immersive gaming and powerful performance with this Gaming Laptop. It features high-performance graphics that deliver stunning visuals and smooth gameplay. The laptop is equipped with a powerful processor and ample storage for seamless multitasking and storage of your gaming library. The sleek and portable design makes it ideal for gaming on the go. Elevate your gaming experience with this high-performance gaming laptop.",
                "rating": 4.5
            },
            {
                "id": 28,
                "company": "lenovo",
                "computer": true,
                "image": "/images/pl2.jpg",
                "name": "Ultrabook with Intel Core i7 Processor",
                "oldPrice": 69999,
                "currentPrice": 64999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 64999,
                "quantityCounter": 1,
                "description": "Get the perfect balance of performance and portability with this Ultrabook. It features an Intel Core i7 processor that delivers powerful and efficient performance for your everyday computing tasks. The slim and lightweight design makes it easy to carry and work on the go. With a high-resolution display and fast storage, this Ultrabook provides a seamless computing experience. Stay productive and stylish with this feature-packed Ultrabook.",
                "rating": 4.2
            },
            {
                "id": 29,
                "company": "asus",
                "computer": true,
                "image": "/images/pl3.jpg",
                "name": "Desktop PC with AMD Ryzen Processor",
                "oldPrice": 57999,
                "currentPrice": 52999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 52999,
                "quantityCounter": 1,
                "description": "Unleash your productivity with this Desktop PC featuring an AMD Ryzen processor. It offers powerful performance for multitasking, content creation, and more. The desktop PC comes with ample storage and memory for storing your files and running demanding applications. The sleek and compact design saves space on your desk. Enhance your work or entertainment experience with this reliable desktop PC.",
                "rating": 4.7
            },
            {
                "id": 30,
                "company": "lenovo",
                "computer": true,
                "image": "/images/pl4.avif",
                "name": "All-in-One PC with Touchscreen Display",
                "oldPrice": 44999,
                "currentPrice": 39999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 39999,
                "quantityCounter": 1,
                "description": "Experience the convenience and versatility of this All-in-One PC with a touchscreen display. It combines the power of a desktop with the compactness of a monitor, eliminating the need for separate components. The touchscreen display allows for intuitive and interactive navigation. With a powerful processor and ample storage, this All-in-One PC is perfect for work and entertainment. Simplify your setup with this stylish and feature-rich All-in-One PC.",
                "rating": 4.0
            },
            {
                "id": 31,
                "company": "samsung",
                "gadgets": true,
                "image": "/images/gad1.jpg",
                "name": "High-Performance Tablet with Retina Display",
                "oldPrice": 8999,
                "currentPrice": 7999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 7999,
                "quantityCounter": 1,
                "description": "Experience high-performance computing on this tablet with a stunning Retina display. Whether you use it for work, entertainment, or creative pursuits, this tablet delivers exceptional performance and visuals. Stay connected, productive, and entertained with the latest features and technologies. The sleek and portable design makes it easy to carry wherever you go.",
                "rating": 4.3
            },
            {
                "id": 32,
                "company": "sony",
                "gadgets": true,
                "image": "/images/gad2.jpg",
                "name": "Professional Drone with 4K Camera",
                "oldPrice": 15999,
                "currentPrice": 13999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 13999,
                "quantityCounter": 1,
                "description": "Capture breathtaking aerial footage with this professional-grade drone equipped with a high-quality 4K camera. Experience the thrill of flying and explore new perspectives as you record stunning videos and capture impressive photos. With advanced features and intuitive controls, this drone is perfect for enthusiasts and professionals alike. Unlock your creativity and take your photography and videography to new heights with this top-of-the-line drone.",
                "rating": 4.8
            },
            {
                "id": 33,
                "company": "sony",
                "gadgets": true,
                "image": "/images/gad3.jpg",
                "name": "Mirrorless Camera with Interchangeable Lenses",
                "oldPrice": 27999,
                "currentPrice": 24999,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 24999,
                "quantityCounter": 1,
                "description": "Unleash your photography skills with this versatile mirrorless camera. Featuring interchangeable lenses and advanced imaging technology, it allows you to capture stunning photos with exceptional clarity and detail. Whether you're a professional photographer or an aspiring enthusiast, this camera offers the perfect balance of performance and portability. Take your photography to the next level with this feature-packed mirrorless camera.",
                "rating": 4.6
            },
            {
                "id": 34,
                "company": "boat",
                "gadgets": true,
                "image": "/images/gad4.jpg",
                "name": "Smartwatch with Fitness Tracking and Heart Rate Monitor",
                "oldPrice": 3999,
                "currentPrice": 3499,
                "estimatedTime": "9 june 2050",
                "isFavorite": false,
                "cartTotal": 3499,
                "quantityCounter": 1,
                "description": "Stay connected and monitor your health and fitness goals with this advanced smartwatch. With built-in fitness tracking features and a heart rate monitor, it helps you stay motivated and achieve your fitness milestones. Stay organized with notifications, track your workouts, and enjoy the convenience of a variety of smart features right on your wrist. Elevate your lifestyle and stay in control with this sleek and functional smartwatch.",
                "rating": 4.4
            },
        ],
    },
    reducers: {
        toggleFavorite: (state, action) => {
            const productId = action.payload;
            state.productsData = state.productsData.map((product) => {
                return product.id == productId ? { ...product, isFavorite: !product.isFavorite } : product;
            });
        },
        addReview: (state, action) => {
            const productId = action.payload.productId
            const reviewData = action.payload.reviewData
            state.productsData = state.productsData.map((product) => {
                return product.id == productId ? { ...product, comments: [...product.comments, reviewData] } : product;
            })
        },
    },
});

export default productDataSlice.reducer;

export const { toggleFavorite, addReview } = productDataSlice.actions;